# Generated by Django 6.0.3 on 2026-04-01 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la matière')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code Matière')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'examen")),
                ('date', models.DateField(verbose_name="Date de l'examen")),
                ('exam_type', models.CharField(choices=[('CC', 'Contrôle Continu'), ('EF', 'Examen Final'), ('DS', 'Devoir Surveillé')], default='CC', max_length=2, verbose_name="Type d'examen")),
                ('total_marks', models.PositiveIntegerField(default=20, verbose_name='Note Maximale')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
            },
        ),
    ]
