# Generated by Django 6.0.3 on 2026-04-01 18:36
# Generated by Django 6.0.3 on 2026-04-01 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_mark'),
        ('student', '0003_alter_student_parent'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='subjects.subject'),
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={},
        ),
        migrations.RemoveField(
            model_name='mark',
            name='remarks',
        ),
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('Quiz', 'Quiz'), ('Midterm', 'Examen Mi-parcours'), ('Final', 'Examen Final')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='mark',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='student.student'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
