# Generated by Django 6.0.3 on 2026-04-01 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('teacher', '0001_initial'),
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={},
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='day',
            new_name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='room_number',
        ),
        migrations.AddField(
            model_name='timetable',
            name='room',
            field=models.CharField(default='Salle 101', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
