
# Generated by Django 6.0.3 on 2026-04-01 10:12

# Generated by Django 6.0.3 on 2026-04-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',

            field=models.CharField(default='pVkByCedH66eEjzgd3IQk1NEj2SCmsWr', editable=False, max_length=32, unique=True),
        ),
    ]
