# Generated by Django 6.0.3 on 2026-04-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='RbQLwe7eDRtqzb7yFDbOjw17IGGEyDVC', editable=False, max_length=32, unique=True),
        ),
    ]
