# Generated by Django 6.0.3 on 2026-04-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0003_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='7gScCllLmXEIw3yPly2NFH1s4PthVgGz', editable=False, max_length=32, unique=True),
        ),
    ]
