# Generated by Django 6.0.3 on 2026-04-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='5xzyb4xUMtMR5pFVKbWwOZ7xAzCEkGpv', editable=False, max_length=32, unique=True),
        ),
    ]
